#!/bin/bash


function link_files () {
    basedir=$1
    reldir=$2
    current_dir=`pwd`
    cd $basedir
    for file in `find . -type f` ; do
        file=${file##./}
        filename=`basename $file`
        target_dir=$(dirname $file)

        if [[ $target_dir != "~"* ]]; then
            target_dir="/${target_dir}"
            sudo=sudo
        else
            target_dir=~/${target_dir##'~'}
        fi
        target_file=$target_dir/$filename
        $sudo rm -f $target_file
        if [[ ! -d $target_dir ]]; then
            mkdir -p $target_dir 2>/dev/null
        fi

        $sudo ln -s "$current_dir/$basedir/$file" $target_file
        sudo=""
    done
    cd $current_dir
}


while true ; do
    case "$1" in
    --link)
        for dir in $2; do
            link_files $dir
        done
        shift
    ;;
    --* | -* )
        echo "unknown option $1, please use --help."
        exit 1
        ;;
    * )
        break
        ;;
    esac
    shift
done
