#!/bin/bash


function link_files () {
  basedir=$1
  cd $basedir
  basedir=`pwd -P`
  find . -type f -print0 |
  while IFS= read -r -d $'\0' file; do
    file=${file##./}
    filename=`basename "$file"`
    target_dir=~/$(dirname "$file")
    target_file="$target_dir/$filename"
    rm -f "$target_file"
    if [[ ! -d "$target_dir" ]]; then
        mkdir -p "$target_dir" 2>/dev/null
    fi

    ln -s "$basedir/$file" "$target_file"
    echo "linking $basedir/$file to $target_file"
  done
  cd -
}


while true ; do
    case "$1" in
    --dirs)
      shift
      config_dir="$1"
      for dir in ${config_dir}/*/; do
        if [[ $dir =~ ^--.* ]]; then
          break
        fi

        link_files $dir
      done
    ;;
    --dir)
      shift
      config_dir="$1"
      link_files $config_dir
    ;;
    --help)
      echo "Usage:"
      echo "    --dirs {parent_dir}  : parent_dir containing multiple config directories"
      echo "    --dir  {config_dir}  : config_dir is a config directory"
      exit 0
      ;;
    --* | -* )
      echo "unknown option $1, please use --help."
      exit 1
      ;;
    * )
      break
      ;;
    esac
    shift
done
